version: '{build}'

init:
  - git config --global core.autocrlf input

configuration: Release

cache: packages -> **\packages.config

build:
  project: framecoder.csproj
  verbosity: minimal

artifacts:
- path: bin/Release
  name: framecoder